using System.Collections.Generic;
using UnityEngine;

namespace FriendsGamesTools
{
    public class NicknameGenerator : SettingsScriptable<NicknameGenerator>
    {
        public static string GetRandomNickname() => instance.options.RandomElement();
        public static string GetNickname(long id) => instance.options[Mathf.Abs((int)id) % instance.options.Count];
        public List<string> options = new List<string>
        {
            "Bad Mr. Frosty",
            "Kraken",
            "Boomer",
            "Lumberjack",
            "Boomerang",
            "Mammoth",
            "Boss",
            "Mastadon",
            "Budweiser",
            "Master",
            "Bullseye",
            "Meatball",
            "Buster",
            "Mooch",
            "Butch",
            "Mr. President",
            "Buzz",
            "Outlaw",
            "Canine",
            "Ratman",
            "Captian RedBeard",
            "Renegade",
            "Champ",
            "Sabertooth",
            "Coma",
            "Scratch",
            "Crusher",
            "Sentinel",
            "Diesel",
            "Speed",
            "Doctor",
            "Spike",
            "Dreads",
            "Subwoofer",
            "Frankenstein",
            "Thunderbird",
            "Froggy",
            "Tornado",
            "General",
            "Troubleshoot",
            "Godzilla",
            "Vice",
            "Hammerhead",
            "Viper",
            "Handy Man",
            "Wasp",
            "Hound Dog",
            "Wizard",
            "Indominus",
            "Zodiac",
            "King Kong",
            "Mammoth",
            "Lobster",
            "Highlander",
            "Mastodon",
            "Slug",
            "Prawn",
            "Canine",
            "Spider",
            "Taz",
            "Ratman",
            "Snake",
            "Sabre-Tooth",
            "Sabertooth",
            "Gecko",
            "Bear",
            "Hammerhead",
            "Dragon",
            "Yak",
            "Viper",
            "Vulture",
            "Zee-donk",
            "Thunderbird",
            "Fish",
            "Dino",
            "Froggy",
            "Jackal",
            "T-Rex",
            "Wasp",
            "Megalodon",
            "Raptor",
            "Hound Dog",
            "Bandicoot",
            "Bird",
            "Wildcat",
            "Bulldog",
            "Gator",
            "Husky",
            "Catfish",
            "Bull",
            "Trunk",
            "Dingo",
            "Longhorn",
            "Boomerang",
            "Sticks",
            "Horsehide",
            "Helmet",
            "Tackle",
            "Hose",
            "The Bat",
            "Wishbone",
            "Hot Box",
            "Field Goal",
            "X",
            "Rain Delay",
            "Touchdown",
            "Z",
            "Interstate",
            "TD",
            "ZD",
            "J-Run",
            "Foul Play",
            "ZB",
            "Junk",
            "Red Flag",
            "Ace",
            "Knuckleball",
            "Endzone",
            "Airmail",
            "Knee-Buckler",
            "Defense",
            "Aspirin",
            "Leather",
            "Offense",
            "Bail",
            "Lights Out",
            "First Down",
            "Banjo Hitter",
            "Lumber",
            "Chip Shot",
            "Barrel",
            "Maddux",
            "Snap",
            "Batter",
            "Masher",
            "Quarterback",
            "Belt",
            "Meat",
            "QB",
            "Big League",
            "Bullseye",
            "LB",
            "Major League",
            "Dart",
            "Flea Flicker",
            "Bigs",
            "Midnight",
            "Fourth Down",
            "Bronx Bomber",
            "Moonshot",
            "FD",
            "Bullpen",
            "Olympus",
            "Fumble",
            "Butcher Boy",
            "Relay",
            "Fullback",
            "Captain Hook",
            "Ribbie",
            "FB",
            "The Chair",
            "Road Game",
            "Gridiron",
            "Cheddar",
            "Rookie",
            "Halfback",
            "Chuck",
            "Room Service",
            "HB",
            "Clinic",
            "Shoe String",
            "Huddle",
            "Cookie",
            "The Show",
            "Interference",
            "Creature",
            "Showboat",
            "Jack",
            "Daisy Cutter",
            "Shut Out",
            "Mo",
            "Dead Red",
            "Sinker",
            "Jumbo",
            "Deuce",
            "Skyscraper",
            "Juke",
            "Earnie",
            "Slap Hitter",
            "Monster Man",
            "Evil Empire",
            "Smoke",
            "NFL",
            "Ump",
            "Southpaw",
            "Pancake",
            "Baller",
            "Stats",
            "Red Shirt",
            "Flamethrower",
            "Stopper",
            "Red Zone",
            "GM",
            "Stretch",
            "Ref",
            "Grand Slam",
            "Tailgate",
            "Rover",
            "Hammer",
            "Tomahawk",
            "Sam",
            "Hat Trick",
            "Uncle Charlie",
            "Sideline",
            "Goalie",
            "Yardwork",
            "Side Zone",
            "Offsides",
            "Zinger",
            "Slobber-knocker",
            "Home Plate",
            "Ballgame",
            "Sneak",
            "Homer",
            "Matchpoint",
            "Split / Splits",
            "Hook",
            "Basket",
            "Boss",
            "Manager",
            "Inventor",
            "Mr. President",
            "The Management",
            "Woodshop",
            "Doctor / Doc",
            "Engineer",
            "Baker",
            "Handyman",
            "The Talent",
            "Chef",
            "Lumberjack",
            "Officer",
            "Astro",
            "Undertaker",
            "The Philosopher",
            "Buzz Aldrin",
            "Henchman",
            "The Pro",
            "Navigator",
            "Judge",
            "Vet",
            "Pilot",
            "Teach",
            "The Specialist",
            "Reverend",
            "Preach",
            "Rep",
            "Detective",
            "VP",
            "HVAC",
            "Inspector",
            "POTUS",
            "Tinker",
            "Undertaker",
            "Commander",
            "Jail Bond",
            "Marine",
            "Outlaw",
            "Bazooka",
            "Boomer",
            "Renegade",
            "Chopper",
            "Boomstick",
            "Champ",
            "The Law",
            "Booter",
            "Sentinel",
            "Bullet",
            "Box Kicker",
            "Colonel",
            "The Enforcement",
            "Captain Jack",
            "Recruit",
            "Howitzer",
            "Doughboy",
            "General",
            "Patrol",
            "FLAK",
            "Air Raid",
            "Platoon",
            "FUBAR",
            "Blitz",
            "Saber",
            "Hoover",
            "Blitzkrieg",
            "Air Alert",
            "Hun",
            "Atomic",
            "Cannon",
            "Iron",
            "Bootleg",
            "Amphibian",
            "Genghis",
            "Guard",
            "HQ",
            "Scuttlebutt",
            "Gunslinger",
            "Armed Force",
            "Trigger",
            "Gunner",
            "Napoleon",
            "Deck",
            "Pistol",
            "Patton",
            "Basecamp",
            "Rifle",
            "Tank",
            "Bomber",
            "AK47",
            "Sub",
            "D-Day",
            "Shield",
            "WMD",
            "Rocket",
            "King Kong",
            "Rocky",
            "Caesar",
            "Godzilla",
            "Robin Hood",
            "Joker",
            "Kraken",
            "Butch Cassidy",
            "Goldfinger",
            "Frankenstein",
            "Sundance Kid",
            "Sherlock",
            "Terminator",
            "Superman",
            "Watson",
            "Mad Max",
            "Tarzan",
            "Grinch",
            "Tin Man",
            "Rooster",
            "Popeye",
            "Scarecrow",
            "Moses",
            "Bullwinkle",
            "Chewbacca",
            "Jesus",
            "Daffy",
            "Han Solo",
            "Zorro",
            "Porky",
            "Captain Redbeard",
            "Batman",
            "Mr. Magoo",
            "Blackbeard",
            "Lincoln",
            "Jetson",
            "HAL",
            "Hannibal",
            "Panther",
            "Wizard",
            "Darth Vader",
            "Gumby",
            "Zodiac",
            "Alien",
            "Underdog",
            "V-Mort",
            "The Shark",
            "Sylvester",
            "C-Brown",
            "Martian",
            "Space Ghost",
            "Finch",
            "Dracula",
            "Felix",
            "Indiana",
            "Kevorkian",
            "Jungle Man",
            "Count",
            "Master",
            "Earl",
            "Cardinal",
            "Knight",
            "Governor",
            "Esquiare",
            "Abbot",
            "Herald",
            "Junior",
            "Admiral of the Fleet",
            "King of Arms",
            "Senior",
            "Professor",
            "Lord Privy Seal",
            "The Third",
            "Baron",
            "Pharoah",
            "Lord Charles",
            "Bishop",
            "Saint",
            "Uncle",
            "Centurion",
            "Sultan",
            "Sir",
            "Don",
            "Tribune",
            "Bad Mr. Frosty",
            "Boomer",
            "Subwoofer",
            "Coma",
            "Buster",
            "Tornado",
            "Scratch",
            "Mooch",
            "Thunder",
            "Crusher",
            "Butch",
            "Lightning",
            "Speed",
            "Buzz",
            "Storm",
            "Troubleshoot",
            "Spike",
            "Bass",
            "Vice",
            "Dreads",
            "Gr8 Beyond",
            "West Coast",
            "Sun Belt",
            "German",
            "East Coast",
            "Bible Belt",
            "High Altitude",
            "Dirty Dirty",
            "Pacific",
            "Lowlands",
            "Rust Belt",
            "Atlantic",
            "CornfedCheese",
            "BBQ",
            "Choco",
            "Meatball",
            "Tex-Mex",
            "Whiskey",
            "Budweiser",
            "Ice",
            "Tango",
            "Mustard",
            "Snicker",
            "Hard-Boiled",
            "Nightcap",
            "Snow Cone",
            "Egg",
            "Salty",
            "Twix",
            "Turk",
            "Pepper",
            "Red Hot",
            "Beef",
            "Ribeye",
            "Tabasco",
            "Belly",
            "Rhubarb",
            "Cornflake",
            "Spice",
            "Seasoning",
            "Crunchie",
            "Sammie",
            "Vinegar",
            "Crisp",
            "Foot-long"
        };
    }
}